### ISSUE TITLE
Project structure explanation

### ISSUE THREAD

**Issue by johnbrett** [ppallesws/isomorphic-hapi#1]
Hi @ppallesws,

Thanks for providing this, I'm interested in Hapi & React in the isomorphic sense.

Can you provide an explanation of the project structure, it seems server.js just returns the clientside React app, and everything is a SPA from there? How would you expand for different pages / views, would you keep everything in the one bundle.js or break things up into different pages, and do you know how would you go about either?

**Comment by ppallesws** [comment]
Hey John,

Sorry but I really haven't had a chance to advance and expound upon this as I had originally intended primarily because I ended up delving into Angular.js rather than React.js.  If I recall, you are correct this little project essentially uses Hapi.js (back-end server-side) to create a wildcard route which offloads the routing logic to React.js (potentially).  That being said... I would suggest you take a look at what Yahoo is doing with Express.js ... generally conversion to Hapi is relatively painless.  https://github.com/yahoo/flux-examples

Let me know what you think and/or find out.  React.js is interesting but I still haven't fully wrapped my head around the whole 'flux architecture' ... nor have I found a need for it.

**Comment by johnbrett** [comment]
Hi @ppallesws,

Thanks for getting back to me, appreciate the honesty and the explanation. I've a lot of experience with Hapi, it's the front end stuff I'm trying to get my head around, but the wildcard route, and letting React do the routing explains all I was looking to know here. 

I prefer React for the server-side rendering ability at the moment, haven't really looked at the flux architecture too much yet, that's for after I've better grasped the routing, templating etc. 

Happy to close this anyway, thanks for your time on this!
